"""Self-training: use the text classifier itself to pseudo-label the ~4349
unlabeled reports in train.csv, keeping only high-confidence predictions, and
add those to the training data. Avoids hand-written multilingual keyword rules
(reports span English, Spanish, German, Dutch, Greek, ...) in favor of letting
the model that already handles that multilinguality (char n-gram TF-IDF) do
the labeling itself.

To stay a fair CV estimate, pseudo-labels used inside compute_oof_pseudo are
generated by a model trained ONLY on that fold's labeled training split, never
using the fold's held-out labeled studies.
"""

import numpy as np
import pandas as pd

from src.config import LABELS
from src.text_baseline import PipelineFactory, build_pipeline


def pseudo_label_confident(
    fitted_pipe,
    unlabeled_texts: np.ndarray,
    threshold: float,
) -> tuple:
    """Returns (texts, hard_labels) for unlabeled examples the model is
    confident about (prob <= 1-threshold or >= threshold)."""
    probs = fitted_pipe.predict_proba(unlabeled_texts)[:, 1]
    confident = (probs >= threshold) | (probs <= 1 - threshold)
    return unlabeled_texts[confident], (probs[confident] >= threshold).astype(int)


def compute_oof_pseudo(
    labeled_df: pd.DataFrame,
    unlabeled_df: pd.DataFrame,
    folds: np.ndarray,
    pipeline_factory: PipelineFactory = build_pipeline,
    thresholds: tuple = (0.9,),
) -> dict:
    """Returns {threshold: oof_dataframe}. Stage 1 (fold-local classifier used
    to score the unlabeled pool) is fit once per (label, fold) and reused
    across all thresholds — only stage 2 (refit on augmented data) repeats
    per threshold, since that's the part whose training set actually changes."""
    texts = labeled_df["Report"].values
    unlabeled_texts = unlabeled_df["Report"].values
    oofs = {t: pd.DataFrame({"StudyInstanceUID": labeled_df["StudyInstanceUID"].values}) for t in thresholds}

    for label in LABELS:
        y = labeled_df[label].values.astype(int)
        preds_by_threshold = {t: np.full(len(y), 0.5) for t in thresholds}
        for fold_id in np.unique(folds):
            train_idx = folds != fold_id
            val_idx = folds == fold_id
            y_train = y[train_idx]
            if len(np.unique(y_train)) < 2:
                for t in thresholds:
                    preds_by_threshold[t][val_idx] = y_train.mean()
                continue

            # Stage 1: fit on this fold's labeled training data only, then
            # score the unlabeled pool with it (no leakage from val fold).
            stage1 = pipeline_factory()
            stage1.fit(texts[train_idx], y_train)
            unlabeled_probs = stage1.predict_proba(unlabeled_texts)[:, 1]

            for t in thresholds:
                confident = (unlabeled_probs >= t) | (unlabeled_probs <= 1 - t)
                pseudo_texts = unlabeled_texts[confident]
                pseudo_labels = (unlabeled_probs[confident] >= t).astype(int)

                aug_texts = np.concatenate([texts[train_idx], pseudo_texts])
                aug_labels = np.concatenate([y_train, pseudo_labels])
                stage2 = pipeline_factory()
                stage2.fit(aug_texts, aug_labels)
                preds_by_threshold[t][val_idx] = stage2.predict_proba(texts[val_idx])[:, 1]
        for t in thresholds:
            oofs[t][label] = preds_by_threshold[t]
    return oofs


def train_final_models_pseudo(
    labeled_df: pd.DataFrame,
    unlabeled_df: pd.DataFrame,
    pipeline_factory: PipelineFactory = build_pipeline,
    threshold: float = 0.9,
) -> dict:
    texts = labeled_df["Report"].values
    unlabeled_texts = unlabeled_df["Report"].values
    models = {}
    for label in LABELS:
        y = labeled_df[label].values.astype(int)
        stage1 = pipeline_factory()
        stage1.fit(texts, y)
        pseudo_texts, pseudo_labels = pseudo_label_confident(stage1, unlabeled_texts, threshold)
        aug_texts = np.concatenate([texts, pseudo_texts])
        aug_labels = np.concatenate([y, pseudo_labels])
        stage2 = pipeline_factory()
        stage2.fit(aug_texts, aug_labels)
        models[label] = stage2
        print(f"  {label:<20} +{len(pseudo_texts)} pseudo-labels ({pseudo_labels.mean():.2f} positive rate)")
    return models
